language: php

if: tag IS present

cache:
  directories:
  - $HOME/.composer/cache

addons:
  apt:
    packages:
    - parallel

php:
- 7.1
- 7.2
- nightly

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly

before_install:
# disable xdebug if available
- phpenv config-rm xdebug.ini || echo "xdebug not available"
# disable default memory limit
- export INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
- echo memory_limit = -1 >> $INI

install:
# flags to pass to install
- flags="--prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
# install dependencies using system provided composer binary
- composer install $flags

script:
- ./artisan admin create-module testm
- ./artisan admin create-ext -b myext
- ls -d tests/**/* | parallel --gnu --keep-order 'echo "Running {} tests"; ./vendor/bin/phpunit -c tests/phpunit.xml --colors=always {} || (echo -e "\e[41mFAILED\e[0m {}" && exit 1);'

before_deploy:
- rm -rf modules/testm extensions/myext storage/report storage/tmp/* storage/logs/*
- composer update --no-dev
- composer dumpautoload -a --no-dev
- echo ".git" >> notar.txt
- echo ".gitattributes" >> notar.txt
- echo "*.log" >> notar.txt
- echo "notar.txt" >> notar.txt
- echo ".travis.yml" >> notar.txt
- tar -czf wulacms-${TRAVIS_TAG}.tar.gz -X notar.txt ./*

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: wulacms-${TRAVIS_TAG}.tar.gz
  skip_cleanup: true
  on:
    tags: true
    branch: v2.0.0
    repo: ninggf/wulacms
    php:  '7.1'