version: "3"
services:
  web:
    container_name: wula_web
    depends_on:
    - php
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
    - "./:/data"
    - "./conf/site.conf:/etc/nginx/conf.d/default.conf:ro"
    working_dir: /data/
    links:
    - "php"
  php:
    container_name: wula_php
    depends_on:
    - "db"
    - "redis"
    image: windywany/php:latest
    volumes:
    - "./:/data"
    working_dir: /data/
    expose:
    - "9000"
    environment:
      XDEBUG_REMOTE_HOST: 172.16.100.200 #请换成你本机的IP(注不是container的IP哦)
      XDEBUG_REMOTE_PORT: 9000
      XDEBUG_ENABLE: 0
    links:
    - "db"
    - "redis"
  db:
    container_name: wula_db
    image: mysql:5.7.23
    expose:
    - "3306"
    volumes:
    - "./storage/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 888888
  redis:
    container_name: wula_redis
    image: redis:4.0.11
    expose:
    - "6379"
    sysctls:
      net.core.somaxconn: 1024